import { writeFileSync } from "fs";
import { resolve } from "path";
import dotenv from "dotenv";

const envConfig = dotenv.config();

if (!envConfig.parsed) {
    throw new Error(".env file not found or empty");
}

const targetPath = resolve("./src/environment/environment.secret.ts");

const header = `/**
AUTOGENERATED IN environment-setup.js
 * ==========================================================
 * Configuration File
 * ----------------------------------------------------------
 * This file defines application-level secrets or endpoints.
 *
 * Important:
 * - Do not commit real production secrets to version control.
 * - This file is intended for development or as a placeholder.
 * - For production, use secure environment handling methods
 *   such as environment variables or secret managers.
 *
 * Usage:
 * Replace placeholder values with actual ones during deployment.
 * Consider using Angular's environment-specific files to manage
 * configurations for different build targets.
 * ==========================================================
 */
`;

let exportsBlock = "";

//If there are /, then we assume that it is a String array
for (const [key, value] of Object.entries(envConfig.parsed)) {
    if (value.includes(",")) {
        const arr = value
            .split(",")
            .map((v) => v.trim())
            .map((v) => `"${v}"`)
            .join(", ");
        exportsBlock += `export const ${key} = [${arr}];\n`;
    } else {
        exportsBlock += `export const ${key} = "${value}";\n`;
    }
}

writeFileSync(targetPath, header + "\n" + exportsBlock);
