-- Add migration script here

--Autogenerated with sqlx migrate add init. El genio de la lampara en otras palabras

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    hashed_password TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    telephone TEXT
);