name: Backend Docker Publish

on:
    push:
        branches:
            - main

jobs:
    back-publish:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                service: [api-gateway, auth-service, call-service, group-service, message-service, notification-service, presence-service, user-service]

        env:
            DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}

        steps:
            - uses: actions/checkout@v3

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker image
              run: |
                  docker build -t $DOCKERHUB_USERNAME/${{ matrix.service }}:latest backend/${{ matrix.service }}

            - name: Push Docker image
              run: |
                  docker push $DOCKERHUB_USERNAME/${{ matrix.service }}:latest
