name: Backend Lint

on:
    push:
        branches:
            - main
            - "back/*"
            - "all/*"
    pull_request:
        branches:
            - main
            - "back/*"
            - "all/*"

jobs:
    fmt-check:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                service: [api-gateway, auth-service, call-service, group-service, message-service, notification-service, presence-service, user-service]

        steps:
            - uses: actions/checkout@v3

            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true

            - name: Check formatting
              run: cargo fmt -- --check
              working-directory: backend/${{ matrix.service }}
