name: Frontend Lint

on:
    push:
        branches:
            - main
            - "front/*"
            - "all/*"
    pull_request:
        branches:
            - main
            - "front/*"
            - "all/*"

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - run: npm ci
              working-directory: ./frontend

            - run: npm run lint
              working-directory: ./frontend
